apiVersion: ENC[AES256_GCM,data:wF8=,iv:T+juJ5Lca5tJgEGTCthuTdrUbqqVg0oEOfSKhURmaRM=,tag:XhHwajNeKEhSqF7ffg15Sw==,type:str]
kind: ENC[AES256_GCM,data:+7okvwb1,iv:G/GTnWmYJZ7ZByayTuJcVW/LnHXN8pA0KpIG2RfGvLQ=,tag:c3wsGAVbscp26rOemDdsrQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hg+OtTfo4RKRKGBSnJ+/xTY=,iv:txAZMfVPfqX7DeWHzd9kSl9dlJGFMxcVOcZmbzdiPSQ=,tag:OtF9BSCZxaSFGmUwDnR6Jg==,type:str]
    namespace: ENC[AES256_GCM,data:uKHhfV8=,iv:R+nU9spx9wpYg5JYsVR2ddX4iaTLx76Owxn1C3O6QcQ=,tag:yw5/RxyoE8FwN0bNn5iJSw==,type:str]
type: ENC[AES256_GCM,data:+WO7xFq7,iv:Arwqeo4qW1P/Wc+Vpzd3ySZzIQIyQjoxeohrDxww8ck=,tag:EO2HvLdQMphMZsvi9eY0cw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:FB5Biw==,iv:uTswDrs+TJD2VuOtvp0ZMqCOiQpMwxL+3nQZLZclQW8=,tag:mVRo6F9CApibV7Fc1zFiSA==,type:str]
    password: ENC[AES256_GCM,data:p+QS1suXnX8KBA==,iv:kfv9yrg3N+GJu3ZH2+iWfX4mAVwfQMU67e6Sb35UV9c=,tag:qMZ69Z0OSw4Eamytjzfw1g==,type:str]
sops:
    age:
        - recipient: age1xmhg74aql2s89wf0putkk86gzqzd2gtg02kpgav9vvczhuyls9usx0989c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwakxJYzdiUk5qUWhkNTl3
            VjgydW1McThXZS9qQ2pIWFFQUHNlOE1SNFNFCldQSWg5QkYzTDJXUXFFb3c2L2xs
            enZnMnRFY0NDcC9ING9jSlJRakxBZG8KLS0tIGNkaC84Tm1DR3R0STFLbGJJaHJB
            dUNUMHV3c3Jnd28yWHpqcUVBeHBNN1EKbp2oc6QuhSQ6Q5IwSHLF/800X2SgLYSY
            sDkLjBsz8d/Xac+rYN7ZMwC0AsmPAhWMrSpqwd7YA4y+jAG/iK/5EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T16:08:59Z"
    mac: ENC[AES256_GCM,data:Oe4/xh2p7JrbMCtY+Kq52CRjJIdcf7kjoC58n0josfTSALDAnUDRe0Xvlnbe3Q1I6QvjeEhk0+OZfUkQjMowhR2/8yUfCNgeGHrPuO9hLd9+ee97vO4/YjaMq4xxTIfVx2DQfv8SMlPQtZqVLoTm6UCpoK9BOsDPUxcVqGZpvJE=,iv:j7ib8UQmByeVkv51/Ax0jqZgvKY+qmmV9oTXSuL0s9U=,tag:o8Dn3+vxdKXm5V1t8spA8Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
