apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql
  namespace: mysql
spec:
  interval: 5m
  chart:
    spec:
      chart: mysql
      version: 9.20.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: mysql
  values:
    auth:
      username: wordpress
      password: example-password
      database: wordpress
    primary:
      persistence:
        enabled: false
