apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: 2.10.2
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: monitoring
  values:
    loki:
      enabled: true
    promtail:
      enabled: true
      config:
        clients:
          - url: http://loki-stack.monitoring.svc.cluster.local:3100/loki/api/v1/push
